### ISSUE TITLE
Consider collaboration with sec-group-broker-filter 

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-community/portcullis#3]
Thanks for sharing this work. 

In case this went unnoticed Orange has contributed very similar work at https://github.com/orange-cloudfoundry/sec-group-broker-filter 

If different programming languages (java vs go-lang) are not an obstacle, it would be interesting to consider collaborating since both efforts that seem to address the same use-cases. Note that the sec-group-broker-filter repo also contains start of a generic framework for broker facades/filters for supporting other uses-cases beyond opening security groups.

Focusing on portcullis, I wonder the rationale for the address mapping that is documented at https://github.com/cloudfoundry-community/portcullis/blob/master/docs/broker_communication.png (and the associated operational burden to maintain a db)

Is this mapping necessary to support dynamic mapped service broker registration (that operations would perform through a dashboard UI)?

In sec-group-broker-filter, we're first planning to support multiple mapped service brokers through deploy-time configuration see https://github.com/orange-cloudfoundry/sec-group-broker-filter/issues/19 and thus currently avoid maintaining state within the sec-group-broker-filter (i.e. no DB is required).

We'd be happy to further exchanges on how to collaborate on this idea.

Thanks in advance,

Guillaume.

/CC @s-bortolussi @poblin-orange

**Comment by thomasmitchell** [comment]
Hello!

So, Portcullis was an idea that came up at the beginning of the year when there actually wasn't anything like it and sat on the back-burner for a long time before we even made a repo for it. We hadn't checked to see if anything had popped up in the meantime to fill the gap and so we had just continued in parallel unknowingly. Race conditions and all that.

If Portcullis was still the idea that it initially was - something to just manage security groups automagically - then there would probably be no discussion here and I'd be writing Java for and deploying your project right now, and saving myself a lot of work in doing so.

For better or worse though, since then, discussions with clients have changed our course to fit more with what the people using this thing would like to see. The course for Portcullis now is more something that allows service creators in larger production environments to have agency to manage their own services availability without needing to funnel through the small subset of folks with full Cloud Foundry administrative privileges to achieve that. Security group management is just one of the things that it will do to aid this, now. We're just trying to take the load of the brokers off of the CF admins where possible.

The database wasn't in the original plan - I wanted to avoid state as much as possible as well. It turned out that in a busier environment where updates to the configuration would be relatively frequent, deployment induced outages to creation of service instances / bindings would give CABs a bit of a panic attack. Also, that defeats some of our purpose, because the folks with BOSH credentials in the Cloud Foundry / Portcullis environments may not be the same people who are deploying their service brokers wherever else - they might not even be doing it with BOSH for whatever reason.

Adding these features to sec-group-broker might not agree with the more concise scope of that project. The project will probably grow even more as we hear more from people we try to use it with. I think collaboration here may do more harm than good, and I think that the separation of use cases between these two projects will grow as time goes on.

Thanks for the heads up that this tool exists, and also for your contribution to the community. 

If you'd like to continue this discussion, I can be found in CF Slack under `tmitchell`. It's a slightly easier medium to have a conversation in. Cheers.

-Tom

**Comment by gberche-orange** [comment]
thanks Tom for this update. We'll continue watching with interest progress, directions and good ideas in portcullis, and will try to share suggestions/ideas/ return-on-experience from the deployment and production operations of sec-group-broker-filter, likely on slack as you suggested.
